### ISSUE TITLE
No RIKA found (connection failed ?)

### ISSUE THREAD

**Issue by antibill51** [MoBOatGVA/Rika-Firenet#1]
Bonjour, 

J'ai enfin trouvé le temps pour tester tout ça, mais malgré le fichier de configuration bien rempli (partie user et mqtt), je bute sur cette erreur.

No RIKA found (connection failed ?)

Comment investiguer pour savoir d'où ça peut venir?

Merci.

**Comment by MoBOatGVA** [comment]
Salut,

Une petite question initiale : tu utilises Python 2.7 ou 3 ?
Le script n'a été testé que sur Python 3, pas certain pour Python 2.7.

Change dans le fichier de configuration; **_system:verbose:_** -> **True**
Ensuite execute-le dans un terminal.

Personnellement, j'ai fait un script sauvé dans /usr/bin appelé "ha-rika" :

```
#!/bin/bash
#
/usr/bin/figlet R I K A
/usr/bin/python3 /[le chemin d'accès au script/rika_domo.py
```

_Note: /usr/bin/figlet est juste un outil graphique pour afficher un truc sympa. Essaie si tu ne connais pas._

Et peux-tu partager ton fichier de configuration en retirant simplement :

```
user:
username et password ?
```

```
mqtt:
L'ip, le client_username et le client_password
```

**Comment by antibill51** [comment]
Bonjour et merci de ta réponse rapide.

J'utilise bien Python3, 
```
root@rastasheep-ubuntu-sshd1:~/Rika-Firenet# python3 --version
Python 3.6.9
```
Je lance pour le moment le script en temps que root.

Voici mon fichier de config : 
```

system:
  url_base: 'https://www.rika-firenet.com' # FIRENET Main page URL
  url_login: '/web/login' # FIRENET Login page partial URL
  url_stove: '/web/stove/' # FIRENET Stove page partial URL
  url_api: '/api/client/' # FIRENET API patirl URL
  json_path: '/root/json' # Local PATH to save JSON file
  verbose: 'True' # Dump the content of the JSON file once process is done - Value : True or False

user:
  username: 'xxx.xxx@gmail.com' # FIRENET User Name
  password: 'xxxxxxx' # FIRENET Password

mqtt:
  server_address: '10.0.4.3' # MQTT IP address
  topic: 'tele/rika/SENSOR' # MQTT Topic (sample: tele/rika/SENSOR)
  client: 'rika' # MQTT Client Name (sample: rika)
  client_username: 'xxxxxx' # MQTT Client Username (if applicable)
  client_password: 'xxxxxx' # MQTT Client Password (if applicable)

```
et le résultat : 

```
root@rastasheep-ubuntu-sshd1:~/Rika-Firenet# /usr/bin/python3 /root/Rika-Firenet/rika_domo.py 
Information : 
               Starting Rika Update (22.02.20 08:11)
               Connecting to Firenet...
               No RIKA found (connection failed ?)
root@rastasheep-ubuntu-sshd1:~/Rika-Firenet# 
```
